### ISSUE TITLE
Query across datasets

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/discovery_api#173]
To support more detailed visualizations, we'll need the ability to query more than one dataset at a time.

- [x] Can query data from 2 or more datasets with one command
- [x] Can't query private tables without proper authentication and authorization

Tech notes:
- Use Presto's `EXPLAIN`
- `POST /api/v1/query` with SQL statement body

**Comment by jdenen** [comment]
Be aware that someone will follow up this work with #174.

**Comment by sukaant** [comment]
Questions:
- What should we expect for the table names?
- Semicolons and SQL Injection
