### ISSUE TITLE
Protect ourselves from multi dataset queries

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/discovery_api#174]
As we make more complicated SQL queries available to end users, we risk leaking private data. We should try to break all of this.

- [ ] @jmorris-pillar can't access data he shouldn't be able to access through the API
- [ ] Can't leak data or table information
- [ ] Fix any issues you find

**Comment by bbrewer-papa-x** [comment]
Look into the following:
- magic comments: https://support.treasuredata.com/hc/en-us/articles/360001457447-Presto-Query-FAQs
- CONFIG directives: https://github.com/prestodb/presto/issues/1062

**Comment by rajones-hntb** [comment]
Findings:

chr(ascii-value) can be used to pass special characters however this did not seem to lead to a vulnerability. hex and base64 encoding can also be used to pass special characters but again, no leaks.

you can pass hive.default.<table_name> in a query which will return valid, but if you give it any other schema, ie hive.whatever.<table_name> it fails. This fingerprints at least part of the system operating behind the scenes.
