### ISSUE TITLE
GeoJSON Visualization Should Not Increment Download Count for Dataset

### ISSUE THREAD

**Issue by bbrewer-papa-x** [smartcitiesdata/discovery_api#194]
It would be nice for the GeoJSON "preview" to be consistent with preview for other datasets. That is, the visualization download should not increment the download counter.
Refer to https://discovery.smartcolumbusos.com/dataset/morpc/1d7e919d_f423_4ba5_b222_6e9978616da1

AC:
- when visiting a GeoJSON dataset page it should not increment the Download Count counter down in the dataset metadata section of the page

**Comment by rob-h-m** [comment]
Changed from enhancement to bug based on discussion w Carrie and Johnson
