### ISSUE TITLE
Create an Existing Google Integration Account and Designed Workflow

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_api#196]
#### User Story: 

As a Smart Columbus developer
I would like to have an existing Google integration account and a designed workflow for using this account in discovery 
So that I have something established to test against when building out the OAuth process for production

#### Acceptance Criteria: 

- [x] A set of details which are consumed from the OAuth process are identified. 
- [x] We have a decision of where and how we will save the captured OAuth data
- [x] It can be demonstrated that the Google OAuth process works. 

#### Technical Details:

- Initially we intend to target the "authorization code" style of Oauth.
- Provide recommendations on what persistent store to use.

#### Amigos:

@jmorris-pillar, @jakeclark

**Comment by bbrewer-papa-x** [comment]
- User clicks on login via google
  - Either Ajax request to API that sends redirect and then react handles the redirect internally
  - Or Button takes you straight to the API/server side page that redirects you to google with auth_code
- Redirect from google hits our auth_code endpoint
  - Either client side routing picks it up and then Ajax passes it to the backend
  - Or API/server side handles the auth_code
- Minimal user details (google UID, provider and email?) are stored in server side


Example flow with POW + POW assent, etc.
- User clicks on login via google in UI
- Goes to the <API/Server>/auth/google/new endpoint
- Gets redirected to Google auth code page and authorizes
- Gets redirected to <API/Server>/auth/google/callback endpoint
- User details (ID, provider, email) are stored in Ecto Repo (PostgreSQL)
- Gets redirected to page of choice - here we would just go back to discovery ui homepage
- We now at least have a cookie stored for <API/Server> host that identifies the user when Ajax calls are made
  - GET <Server>/api/v1/charts - server has `conn.assigns.current_user` to look that up with
  - PUT <Server>/api/v1/chart - server has `conn.assigns.current_user` to look that up with


What about Guardian?
It "should" sit alongside things for starts. Ultimately, we could:
- Move Paddle based auth stuff into a Pow Strategy
- Move Guardian token plug into a Pow compatible plug like this https://github.com/danschultzer/pow/tree/master#authorization-plug (or swap it out for Phoenix.Token)
- Now have a unified handle to the user via `conn.assigns.current_user` as referenced in the Ecto database

**Comment by bbrewer-papa-x** [comment]
Example of using POW + POW Assent + Google

https://github.com/SmartColumbusOS/oauth-pow-demo
