### ISSUE TITLE
SPIKE: Determine path forward in support of PII requirements

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_api#197]
The OS has a strict requirement that no PII can exist in the system.  The introduction of OAuth has the potential of capturing PII on behalf of individual users of the OS.  The scope of this card is to determine the following: 

- [ ] What data points have the potential to be stored in the OAuth process?
- [ ] Is it considered PII if the user is self-submitting the information? 
- [ ] At what point is data considered "in the OS"? 
- [ ] Do we have the ability to create user profiles/the ability to favorite data sets within the PII requirements? 

The outcome of answering these questions will inform the path forward with implementing OAuth.

Amigos: 
@jmorris-pillar , @carriebrinkley , Warner Moore, @jeffgrunewald

**Comment by jeffgrunewald** [comment]
In support of the "at what point is data considered to be 'in the OS'" AC, can we get clarification about "persisted/stored vs. in memory/processing"? I can imagine a lot of additional use cases where data containing PII enters the ingestion pipeline but is scrubbed or scrambled before is can be stored or streamed out if we can define "in the OS" something like "data is stored and accessible to users or operators via standard query operations or api requests"

**Comment by carriebrinkley** [comment]
Answers to the questions above: 

1.) Depends on how it is implemented - idea is that it would be email and password.
2.) Yes, it still is considered PII if the user is self-submitting.  For OAuth, the user is submitting a username and email address.  
3.) TBD after a further conversation.
4.) At this time we do not based on what is written in the DPP and co-operative agreement.
