### ISSUE TITLE
Connect Auth0 to Google 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_api#198]
#### User Story:

As Connor 
I would like to be able to have a personalized experience in the discovery apps
So that I can favorite datasets, create charts, and return to them in the future

#### Business Value: 

1.) Lays the foundation for improved user experience in the OS through personalization 
2.) Continued separation between public and restricted datasets 
3.) Risk reduction by implementing through Google

#### Acceptance Criteria:

- [ ] There exists a Google login button on the discovery login page
- [ ] When the button is clicked and the OAuth is complete, the user is redirected to discovery as "logged on" 
- [ ] There is a persistent store that associates accounts to some token/identifier 
- [ ] Private dataset users will still login with the old LDAP process 
- [ ] The user is able to log out of the system

#### Technical Notes:

1.) Jake Clark to provide mockups of the UI 
2.) Authorization code style of OAuth should be used 
3.) Be sure to adhere to PII requirements determined through #discovery_api#197
4.) Whitelist discovery domains only.
5.) This should be set up with some account level google account.
6.) Authorization tokens should not be exposed to the client

#### Amigos: 

@jmorris-pillar , @carriebrinkley , @jakeclark

**Comment by rob-h-m** [comment]
Rejecting - new card to be written for Auth0 approach
