### ISSUE TITLE
Create ability for user to revoke application access for OAuth

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_api#200]
#### User Story: 

As Connor
I would like to be able to delete/revoke application access from my OAuth
So that I maintain control over my own privacy

#### Business Value: 

1.) Positive user experience 
2.) Maintain an accurate list of active users 

#### Acceptance Criteria: 

- [ ] The user is able to delete/revoke permissions on their account 
- [ ] Any information held about the user is soft-deleted from the database when the action is completed by the user

#### Technical Notes: 

- [ ] @jakeclark will provide guidance on the flow/language for this action 
- [ ] @jmorris-pillar will update what information is held about the user based on the outcome of #discovery_api#197

#### Amigos: 

@jmorris-pillar , @carriebrinkley , @jakeclark

**Comment by rob-h-m** [comment]
Covered by discovery_ui #208
