### ISSUE TITLE
Configure OAuth account for google

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/discovery_api#205]
If google is our first choice for oauth providers we will need an account which is controlled by the program for this to be configured under.

AC:

- [ ] A set of Google OAuth account(s) are created for testing and prod sites

Tech Notes:
- We should use a smart columbus level google account controlled by leadership for this integration.

**Comment by rob-h-m** [comment]
rejected 08/14/19 by Carrie and Johnson
