### ISSUE TITLE
Discovery API Saves Organization On organization:update Events

### ISSUE THREAD

**Issue by abrock-accenture** [smartcitiesdata/discovery_api#257]
This will allow us to create a relationship between users of Discovery API and organizations

ACs:
- Organizational updates are persisted within discovery API and are displayed in discovery UI
- Historical organizations have been migrated to the event stream

Tech notes:
- The operation to store the organization should be idempotent
- This is going to introduce the event stream to discovery API

**Comment by abrock-accenture** [comment]
@jdenen and/or @jeffgrunewald Please verify this jives with the architectural direction of the system

**Comment by jeffgrunewald** [comment]
I agree with this; regardless of whether or not Discovery API uses Postgres or Redis for its event stream view state, is there already a card created to make Discovery API aware of the event stream? That would be a pre-req for this card but this could probably be a very early card played once the application is aware of Brook.

**Comment by ManApart** [comment]
TODO:

- [ ] update org controller
- [ ] use schema on metadata_view instead of org from model
- [ ] save org to ecto on brook update
- [ ] add org id when saving model
- [ ] remove org from model

----

Stretch goals:
- [ ] Divo modules rather than docker-compose.yaml
- [ ] Address possible performance issue of looking up org for each LDAP check

**Comment by abrock-accenture** [comment]
More thoughts:

- handle more cases where org is not available
- Need some kind of caching layer for looking up a organizations?  How bad is performance now for services like `data_json` and `search`?
- We should probably be integration testing with event stream `organization:update` events rather than putting organizations directly into postgres.  :sigh:
