### ISSUE TITLE
[discovery-api] modifiedDate not being updated

### ISSUE THREAD

**Issue by smillardHNTB** [smartcitiesdata/discovery_api#298]
discovery-api currently reads the forklift:last_insert_date from redis but that value is no longer updated.  This is causing the ability to sort by modified date on discovery-ui to not work correctly.

related:
https://github.com/smartcitiesdata/smartcitiesdata/issues/206

**Comment by carriebrinkley** [comment]
Prioritized work to fix the problem.  Closing bug.
