### ISSUE TITLE
Create performance test

### ISSUE THREAD

**Issue by mcsearchin** [smartcitiesdata/discovery_api#305]
AC:
- Developers should be able to look at an HTML report that gives them current and historical timing statistics for typical web requests. These can be against a local API instance. 
- Example requests:
  - default search
  - search with search text, filter and sorting
  - dataset detail view
  - dataset data download

Tech Notes:
- The spike for this (smartcitiesdata/smartcitiesdata#288) recommends doing this with Benchee wrapping some web calls. Benchee gives some decent repetition for getting averages, standard deviation, etc.
- One solution could save and archive the Benchee results as a .benchee file and then load them in on the next run. For load and saving Benchee results for historical access - https://github.com/bencheeorg/benchee#saving-loading-and-comparing-previous-runs
- For generating HTML reports for a run - https://github.com/bencheeorg/benchee_html
- Jenkins (maybe travis too) can archive those files, so they can be loaded for the next run
- Benchee reports with history in them can get kind of slow. A rolling window of 10 previous runs might be most performant. For this, the Benchee.load and Benchee.Formatters.TaggedSave should be of use (https://github.com/bencheeorg/benchee/blob/05dbe4f5c4e2c5ae08cd8f2eddea21bea4cba196/lib/benchee/configuration.ex)

Amigos: 
@bbrewer-papa-x , @JarredOlson

**Comment by jakeprem** [comment]
I know we already spiked out a solution for this, but two more options I came across that might be worth considering:
  * https://www.sitespeed.io/
  * https://github.com/theodo/falco

Some (small) amount of discussion on these tools can be found here: https://news.ycombinator.com/item?id=21782714
